name: 'Label Actions'

on:
  issues:
    types: [labeled]

jobs:
  reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@201c706f66d13baf871b4af784bbdb7555e983b4 # v2.1.3
        with:
          github-token: ${{ github.token }}
          process-only: 'issues'
